"use client"

import { useEffect, useRef, useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { toast } from "sonner"
import { Loader2, RefreshCw, Shield } from "lucide-react"

export default function AdminLoginPage() {
  const router = useRouter()
  const [isLoading, setIsLoading] = useState(false)
  const [captchaImage, setCaptchaImage] = useState("")
  const [captchaAnswer, setCaptchaAnswer] = useState("")
  const [captchaLoading, setCaptchaLoading] = useState(true)
  const [captchaError, setCaptchaError] = useState("")
  const captchaRequest = useRef(false)

  const refreshCaptcha = async () => {
    if (captchaRequest.current) return
    captchaRequest.current = true
    setCaptchaLoading(true)
    setCaptchaImage("")
    setCaptchaAnswer("")
    setCaptchaError("")
    try {
      const response = await fetch("/api/admin/login/captcha", { cache: "no-store" })
      const data = await response.json()
      if (!response.ok) throw new Error(data.error || "Unable to load CAPTCHA")
      setCaptchaImage(data.image)
    } catch (error) {
      setCaptchaError(error instanceof Error ? error.message : "Unable to load CAPTCHA")
    } finally {
      captchaRequest.current = false
      setCaptchaLoading(false)
    }
  }

  useEffect(() => { void refreshCaptcha() }, [])
  const [formData, setFormData] = useState({
    email: "",
    password: ""
  })

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!formData.email || !formData.password) {
      toast.error("Please enter email and password")
      return
    }
    if (!captchaImage || !captchaAnswer.trim() || captchaLoading || isLoading) {
      toast.error("Please enter the CAPTCHA code")
      return
    }

    setIsLoading(true)

    try {
      const response = await fetch("/api/admin/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ...formData, captchaAnswer })
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || "Login failed")
      }

      toast.success("Login successful!")
      router.push("/admin")
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Login failed")
      await refreshCaptcha()
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-background to-muted/30 p-4">
      <Card className="max-w-md w-full">
        <CardHeader className="text-center">
          <div className="flex items-center justify-center gap-2 mb-2">
            <Image src="/Certistage_icon.svg" alt="CertiStage" width={36} height={36} />
            <span className="font-semibold text-xl">CertiStage</span>
          </div>
          <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-2">
            <Shield className="h-6 w-6 text-primary" />
          </div>
          <CardTitle>Host Panel Login</CardTitle>
          <CardDescription>Sign in to access admin dashboard</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                autoComplete="username"
                required
                placeholder="admin@example.com"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                autoComplete="current-password"
                required
                placeholder="Enter password"
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="captcha">Security verification</Label>
              <div className="flex items-center gap-3 rounded-lg border border-gold/25 bg-gold-soft/30 p-2">
                <div className="flex h-[76px] min-w-0 flex-1 items-center justify-center" aria-live="polite">
                  {captchaLoading ? <Loader2 className="h-5 w-5 animate-spin text-gold-deep" aria-label="Loading CAPTCHA" /> : captchaImage ? (
                    // The image is generated by our server and includes no external URL.
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={captchaImage} alt="CAPTCHA code. Enter the six characters shown below." width={250} height={76} className="h-[76px] max-w-full object-contain" />
                  ) : <p className="text-sm text-destructive">{captchaError}</p>}
                </div>
                <Button type="button" variant="outline" size="icon" onClick={() => void refreshCaptcha()} disabled={captchaLoading || isLoading} aria-label="Refresh CAPTCHA" className="shrink-0 border-gold/30 text-gold-deep hover:bg-gold-soft">
                  <RefreshCw className="h-4 w-4" />
                </Button>
              </div>
              <Input id="captcha" value={captchaAnswer} onChange={(e) => setCaptchaAnswer(e.target.value.toUpperCase())} placeholder="Enter the 6-character code" autoComplete="off" autoCapitalize="characters" spellCheck={false} maxLength={6} required disabled={captchaLoading || !captchaImage || isLoading} aria-describedby="captcha-help" />
              <p id="captcha-help" className="text-xs text-muted-foreground">Code expires in 5 minutes. Use refresh for a new code.</p>
            </div>

            <Button type="submit" className="w-full" disabled={isLoading || captchaLoading || !captchaImage}>
              {isLoading ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Signing in...
                </>
              ) : (
                "Sign In"
              )}
            </Button>
          </form>

          <div className="mt-6 text-center">
            <Link href="/" className="text-sm text-muted-foreground hover:text-primary">
              ← Back to Home
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
