"use client"

import { useEffect, useRef, useState } from "react"
import { AdminHeader } from "@/components/admin/admin-header"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Mail, Search, Eye, Trash2, RefreshCw, Download, Loader2, ChevronLeft, ChevronRight, AlertCircle, RotateCcw } from "lucide-react"
import { toast } from "sonner"
import { cn } from "@/lib/utils"
import { EMAIL_STATUSES, emailLogDate, emailTemplateLabel, emailPreviewDocument, type AdminEmailLog } from "@/lib/admin-email-logs"

const labels: Record<string, string> = { initiated: "Initiated", sent: "Sent", failed: "Failed", read: "Read" }
const colors: Record<string, string> = { initiated: "bg-amber-50 text-amber-700", sent: "bg-emerald-50 text-emerald-700", failed: "bg-rose-50 text-rose-700", read: "bg-blue-50 text-blue-700" }
function StatusBadge({ status }: { status: string }) { return <Badge variant="outline" className={cn("gap-1.5 rounded-full border-0 px-2.5 py-1 font-medium", colors[status])}><span className="h-1.5 w-1.5 rounded-full bg-current" />{labels[status] || status}</Badge> }

export default function EmailLogsPage() {
  const [logs, setLogs] = useState<AdminEmailLog[]>([])
  const [search, setSearch] = useState(""); const [debouncedSearch, setDebouncedSearch] = useState("")
  const [status, setStatus] = useState("all"); const [template, setTemplate] = useState("all"); const [dateRange, setDateRange] = useState("all"); const [sort, setSort] = useState("newest")
  const [page, setPage] = useState(1); const [limit, setLimit] = useState("20"); const [refresh, setRefresh] = useState(0)
  const [pagination, setPagination] = useState({ page: 1, limit: 20, total: 0, totalPages: 1 })
  const [stats, setStats] = useState<Record<string, number>>({ total: 0, initiated: 0, sent: 0, failed: 0, read: 0 })
  const [templates, setTemplates] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  const [exporting, setExporting] = useState(false)
  const [previewId, setPreviewId] = useState<string | null>(null); const [preview, setPreview] = useState<AdminEmailLog | null>(null); const [previewError, setPreviewError] = useState(""); const [previewLoading, setPreviewLoading] = useState(false)
  const [deleteLog, setDeleteLog] = useState<AdminEmailLog | null>(null); const [deleting, setDeleting] = useState(false)
  const searchSequence = useRef(0)
  useEffect(() => { const timer = setTimeout(() => { setDebouncedSearch(search); setPage(1) }, 350); return () => clearTimeout(timer) }, [search])
  const params = new URLSearchParams({ search: debouncedSearch, status, template, dateRange, sort, page: String(page), limit }).toString()
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError("")
    fetch(`/api/admin/email-logs?${params}`, { signal: controller.signal }).then(async res => { const data = await res.json(); if (!res.ok) throw Error(data.error || "Unable to load logs"); return data }).then(data => { setLogs(data.logs); setPagination(data.pagination); setStats(data.stats); setTemplates(data.templates) }).catch(err => { if (!controller.signal.aborted) setError(err.message) }).finally(() => { if (!controller.signal.aborted) setLoading(false) })
    return () => controller.abort()
  }, [params, refresh])
  useEffect(() => {
    if (!previewId) return
    const controller = new AbortController(); const sequence = ++searchSequence.current
    setPreview(null); setPreviewError(""); setPreviewLoading(true)
    fetch(`/api/admin/email-logs/${previewId}`, { signal: controller.signal }).then(async res => { const data = await res.json(); if (!res.ok) throw Error(data.error || "Unable to load email"); return data }).then(data => { if (sequence === searchSequence.current) setPreview(data) }).catch(err => { if (!controller.signal.aborted) setPreviewError(err.message) }).finally(() => { if (!controller.signal.aborted) setPreviewLoading(false) })
    return () => controller.abort()
  }, [previewId])
  function reset() { setSearch(""); setDebouncedSearch(""); setStatus("all"); setTemplate("all"); setDateRange("all"); setSort("newest"); setPage(1) }
  async function exportCsv() {
    setExporting(true)
    try { const res = await fetch(`/api/admin/export/email-logs?${params}`); if (!res.ok) throw Error((await res.json()).error || "Export failed"); const url = URL.createObjectURL(await res.blob()); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "email-logs.csv"; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) } catch (err) { toast.error(err instanceof Error ? err.message : "Export failed") } finally { setExporting(false) }
  }
  async function removeLog() {
    if (!deleteLog) return; setDeleting(true)
    try { const res = await fetch(`/api/admin/email-logs/${deleteLog.id}`, { method: "DELETE" }); if (!res.ok) throw Error((await res.json()).error || "Delete failed"); setDeleteLog(null); setRefresh(value => value + 1); toast.success("Email log deleted") } catch (err) { toast.error(err instanceof Error ? err.message : "Delete failed") } finally { setDeleting(false) }
  }
  return <>
    <AdminHeader title="Email Logs" compact />
    <main className="min-w-0 flex-1 overflow-auto bg-slate-50/40 p-4 md:p-6">
      <div className="mx-auto max-w-[1600px] space-y-6">
        <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">Email Logs</h1><p className="mt-1 text-sm text-muted-foreground">Monitor outgoing emails, investigate failures and review message content.</p></div><div className="flex gap-2"><Button variant="outline" className="bg-white" onClick={exportCsv} disabled={loading || !!error || exporting || pagination.total === 0}>{exporting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}Export CSV</Button><Button variant="outline" className="border-gold/35 bg-white text-gold-deep hover:bg-gold-soft" onClick={() => setRefresh(value => value + 1)} disabled={loading}><RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} />Refresh</Button></div></div>
        <div className="flex flex-wrap gap-2" aria-label="Filter by email status">{["all", ...EMAIL_STATUSES].map(value => <Button key={value} variant="outline" size="sm" aria-pressed={status === value} className={cn("rounded-lg bg-white", status === value && "border-gold/35 bg-gold-soft text-gold-deep")} onClick={() => { setStatus(value); setPage(1) }}>{value === "all" ? "All emails" : labels[value]}<span className="ml-1 text-xs opacity-65">{loading || error ? "—" : (stats[value === "all" ? "total" : value] || 0).toLocaleString("en-IN")}</span></Button>)}</div>
        <div className="flex flex-wrap gap-3"><div className="relative min-w-[200px] flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Search emails" placeholder="Search recipient or subject..." className="h-10 bg-white pl-9" value={search} onChange={e => setSearch(e.target.value)} /></div>
          <Select value={template} onValueChange={value => { setTemplate(value); setPage(1) }}><SelectTrigger className="h-10 w-[190px] bg-white" aria-label="Email template"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All templates</SelectItem>{templates.map(value => <SelectItem value={value} key={value}>{emailTemplateLabel(value)}</SelectItem>)}</SelectContent></Select>
          <Select value={dateRange} onValueChange={value => { setDateRange(value); setPage(1) }}><SelectTrigger className="h-10 w-[155px] bg-white" aria-label="Date range"><SelectValue /></SelectTrigger><SelectContent>{[["all", "All time"], ["today", "Today (IST)"], ["week", "Last 7 days"], ["month", "Last 30 days"]].map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>
          <Button variant="outline" className="h-10 bg-white" onClick={reset}><RotateCcw className="h-4 w-4"/>Reset</Button>
        </div>
        <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground"><p>Status counts follow your search, template and date filters. Times shown in IST.</p><Select value={sort} onValueChange={value => { setSort(value); setPage(1) }}><SelectTrigger className="h-8 w-[145px] bg-white" aria-label="Sort emails"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="newest">Newest first</SelectItem><SelectItem value="oldest">Oldest first</SelectItem></SelectContent></Select></div>
        <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><Table><TableHeader className="bg-slate-50/70"><TableRow><TableHead className="w-14 pl-5">#</TableHead><TableHead>Recipient</TableHead><TableHead>Message</TableHead><TableHead>Template</TableHead><TableHead>Status</TableHead><TableHead>Created (IST)</TableHead><TableHead className="pr-5 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>
          {loading ? <TableRow><TableCell colSpan={7} className="h-48 text-center"><Loader2 className="mx-auto mb-3 h-5 w-5 animate-spin text-gold-deep"/>Loading email logs...</TableCell></TableRow> : error ? <TableRow><TableCell colSpan={7} className="h-48 text-center"><AlertCircle className="mx-auto mb-2 h-6 w-6 text-rose-500"/><p className="mb-3">{error}</p><Button variant="outline" onClick={() => setRefresh(value => value + 1)}>Try again</Button></TableCell></TableRow> : logs.length === 0 ? <TableRow><TableCell colSpan={7} className="h-48 text-center"><Mail className="mx-auto mb-3 h-7 w-7 text-gold-deep"/><p className="font-medium">No email logs found</p><p className="mt-1 text-sm text-muted-foreground">Try changing your filters or searching another recipient.</p><Button variant="ghost" className="mt-2 text-gold-deep" onClick={reset}>Clear filters</Button></TableCell></TableRow> : logs.map((log, index) => <TableRow key={log.id} className="hover:bg-gold-soft/20"><TableCell className="pl-5 text-muted-foreground">{(pagination.page - 1) * pagination.limit + index + 1}</TableCell><TableCell className="min-w-[230px]"><p className="font-medium">{log.to}</p>{log.metadata?.userName && <p className="mt-1 text-xs text-muted-foreground">{log.metadata.userName}</p>}</TableCell><TableCell className="min-w-[250px] max-w-[350px]"><button className="block max-w-full truncate text-left hover:text-gold-deep" title={log.subject} onClick={() => setPreviewId(log.id)}>{log.subject}</button>{log.errorMessage && <p className="mt-1 max-w-[300px] truncate text-xs text-rose-600" title={log.errorMessage}>{log.errorMessage}</p>}</TableCell><TableCell><Badge variant="outline" className="whitespace-nowrap font-normal text-muted-foreground">{emailTemplateLabel(log.template)}</Badge></TableCell><TableCell><StatusBadge status={log.status}/></TableCell><TableCell className="whitespace-nowrap text-xs text-muted-foreground">{emailLogDate(log.createdAt)}</TableCell><TableCell className="pr-4"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" aria-label={`View email to ${log.to}`} onClick={() => setPreviewId(log.id)}><Eye className="h-4 w-4"/></Button><Button variant="ghost" size="icon" aria-label={`Delete log for ${log.to}`} onClick={() => setDeleteLog(log)} className="text-muted-foreground hover:text-rose-600"><Trash2 className="h-4 w-4"/></Button></div></TableCell></TableRow>)}
        </TableBody></Table></div>
        <div className="flex flex-wrap items-center justify-between gap-4 text-sm"><p className="text-muted-foreground">{loading ? "Loading results…" : error ? "Results unavailable" : `Showing ${pagination.total ? (pagination.page - 1) * pagination.limit + 1 : 0} to ${Math.min(pagination.page * pagination.limit, pagination.total)} of ${pagination.total.toLocaleString("en-IN")} results`}</p><div className="flex flex-wrap items-center gap-2"><Select value={limit} onValueChange={value => { setLimit(value); setPage(1) }}><SelectTrigger className="h-9 w-[100px] bg-white" aria-label="Rows per page"><SelectValue /></SelectTrigger><SelectContent>{["10", "20", "50"].map(value => <SelectItem value={value} key={value}>{value} rows</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" disabled={loading || !!error || pagination.page <= 1} onClick={() => setPage(pagination.page - 1)} aria-label="Previous page"><ChevronLeft className="h-4 w-4"/></Button><span className="px-1 text-xs text-muted-foreground">Page {pagination.page} of {pagination.totalPages}</span><Button variant="outline" size="sm" disabled={loading || !!error || pagination.page >= pagination.totalPages} onClick={() => setPage(pagination.page + 1)} aria-label="Next page"><ChevronRight className="h-4 w-4"/></Button></div></div>
        <p className="text-xs text-muted-foreground">“Sent” records a successful send operation, not confirmed inbox delivery. “Read” appears only when recorded by the system.</p>
      </div>
    </main>
    <Dialog open={!!previewId} onOpenChange={open => { if (!open) setPreviewId(null) }}><DialogContent className="w-[96vw] sm:max-w-5xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>Email details</DialogTitle><DialogDescription>Review the recorded message and send status.</DialogDescription></DialogHeader>{previewLoading ? <Loader2 className="mx-auto my-16 h-6 w-6 animate-spin text-gold-deep"/> : previewError ? <p className="py-8 text-center text-destructive">{previewError}</p> : preview ? <div className="min-w-0 space-y-4"><div className="grid gap-4 rounded-lg border bg-slate-50/60 p-4 text-sm sm:grid-cols-2">{[["Recipient", preview.to], ["Template", emailTemplateLabel(preview.template)], ["Created (IST)", emailLogDate(preview.createdAt)], ["Sent (IST)", emailLogDate(preview.sentAt)], ["Read (IST)", emailLogDate(preview.readAt)]].map(([label, value]) => <div key={label}><p className="mb-1 text-xs text-muted-foreground">{label}</p><p className="break-words">{value}</p></div>)}<div><p className="mb-1 text-xs text-muted-foreground">Status</p><StatusBadge status={preview.status}/></div><div className="sm:col-span-2"><p className="mb-1 text-xs text-muted-foreground">Subject</p><p className="break-words font-medium">{preview.subject}</p></div></div>{preview.errorMessage && <div className="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><p className="mb-1 font-medium">Send failure</p><p className="break-words">{preview.errorMessage}</p></div>}{preview.htmlContent ? <iframe sandbox="" referrerPolicy="no-referrer" srcDoc={emailPreviewDocument(preview.htmlContent)} title="Email content preview" className="h-[480px] w-full rounded-lg border bg-white"/> : <p className="py-8 text-center text-muted-foreground">No email content stored for this log.</p>}</div> : null}</DialogContent></Dialog>
    <Dialog open={!!deleteLog} onOpenChange={open => { if (!open && !deleting) setDeleteLog(null) }}><DialogContent><DialogHeader><DialogTitle>Delete email log?</DialogTitle><DialogDescription>This permanently removes the stored log and preview for {deleteLog?.to}. It does not recall the email.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" disabled={deleting} onClick={() => setDeleteLog(null)}>Cancel</Button><Button variant="destructive" disabled={deleting} onClick={removeLog}>{deleting ? "Deleting…" : "Delete log"}</Button></DialogFooter></DialogContent></Dialog>
  </>
}

