"use client"
import { useEffect, useState } from "react"
import { AdminHeader } from "@/components/admin/admin-header"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Search, RefreshCw, Loader2, RotateCcw, MessageSquare, ChevronLeft, ChevronRight, Eye, AlertCircle } from "lucide-react"
import { cn } from "@/lib/utils"
import { TICKET_LABELS, TICKET_STATUSES, ticketNeedsReply, type AdminTicket } from "@/lib/admin-support"
import { emailLogDate } from "@/lib/admin-email-logs"
import { TicketDialog } from "@/components/admin/support/ticket-dialog"

const colors = { open: "bg-amber-50 text-amber-700", in_progress: "bg-blue-50 text-blue-700", closed: "bg-emerald-50 text-emerald-700" }
export default function AdminSupportPage() {
  const [tickets, setTickets] = useState<AdminTicket[]>([]); const [counts, setCounts] = useState<Record<string, number>>({ open: 0, in_progress: 0, closed: 0 })
  const [search, setSearch] = useState(""); const [debouncedSearch, setDebouncedSearch] = useState("")
  const [status, setStatus] = useState("open"); const [plan, setPlan] = useState("all"); const [response, setResponse] = useState("all"); const [dateRange, setDateRange] = useState("all"); const [sort, setSort] = useState("newest")
  const [plans, setPlans] = useState<string[]>([]); const [page, setPage] = useState(1); const [limit, setLimit] = useState("20")
  const [pagination, setPagination] = useState({ page: 1, limit: 20, total: 0, totalPages: 1 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [refresh, setRefresh] = useState(0); const [selectedId, setSelectedId] = useState<string | null>(null)
  useEffect(() => { const timer = setTimeout(() => { setDebouncedSearch(search); setPage(1) }, 350); return () => clearTimeout(timer) }, [search])
  const params = new URLSearchParams({ search: debouncedSearch, status, plan, response, dateRange, sort, page: String(page), limit }).toString()
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError("")
    fetch(`/api/admin/support?${params}`, { signal: controller.signal }).then(async res => { const data = await res.json(); if (!res.ok) throw Error(data.error || "Unable to load tickets"); return data }).then(data => { setTickets(data.tickets); setCounts(data.counts); setPlans(data.plans); setPagination(data.pagination) }).catch(err => { if (!controller.signal.aborted) setError(err.message) }).finally(() => { if (!controller.signal.aborted) setLoading(false) })
    return () => controller.abort()
  }, [params, refresh])
  function reset() { setSearch(""); setDebouncedSearch(""); setStatus("all"); setPlan("all"); setResponse("all"); setDateRange("all"); setSort("newest"); setPage(1) }
  return <><AdminHeader title="Support" compact/><main className="min-w-0 flex-1 overflow-auto bg-slate-50/40 p-4 md:p-6"><div className="mx-auto max-w-[1600px] space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold tracking-tight">Support</h1><p className="mt-1 text-sm text-muted-foreground">Manage customer requests, follow conversations and resolve issues.</p></div><Button variant="outline" className="border-gold/35 bg-white text-gold-deep hover:bg-gold-soft" disabled={loading} onClick={() => setRefresh(value => value + 1)}><RefreshCw className={cn("h-4 w-4", loading && "animate-spin")}/>Refresh</Button></div>
    <div className="flex flex-wrap gap-2" aria-label="Filter tickets by status">{["all", ...TICKET_STATUSES].map(value => <Button variant="outline" size="sm" key={value} aria-pressed={status === value} className={cn("rounded-lg bg-white", status === value && "border-gold/35 bg-gold-soft text-gold-deep")} onClick={() => { setStatus(value); setPage(1) }}>{value === "all" ? "All tickets" : TICKET_LABELS[value as keyof typeof TICKET_LABELS]}<span className="ml-1 text-xs opacity-65">{loading || error ? "—" : (value === "all" ? Object.values(counts).reduce((a,b) => a+b,0) : counts[value] || 0).toLocaleString("en-IN")}</span></Button>)}</div>
    <div className="flex flex-wrap gap-3"><div className="relative min-w-[200px] flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Search tickets" className="h-10 bg-white pl-9" placeholder="Search ticket, subject, customer or organization..." value={search} onChange={event => setSearch(event.target.value)}/></div>
      <Select value={response} onValueChange={value => { setResponse(value); setPage(1) }}><SelectTrigger aria-label="Response filter" className="h-10 w-[185px] bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All conversations</SelectItem><SelectItem value="awaiting">Awaiting response</SelectItem></SelectContent></Select>
      <Select value={plan} onValueChange={value => { setPlan(value); setPage(1) }}><SelectTrigger aria-label="Customer plan" className="h-10 w-[155px] bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All plans</SelectItem>{plans.map(value => <SelectItem key={value} value={value}><span className="capitalize">{value}</span></SelectItem>)}</SelectContent></Select>
      <Select value={dateRange} onValueChange={value => { setDateRange(value); setPage(1) }}><SelectTrigger aria-label="Created date range" className="h-10 w-[155px] bg-white"><SelectValue/></SelectTrigger><SelectContent>{[["all","All time"],["today","Today (IST)"],["week","Last 7 days"],["month","Last 30 days"]].map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Button variant="outline" className="h-10 bg-white" onClick={reset}><RotateCcw className="h-4 w-4"/>Reset</Button>
    </div><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Status counts follow your search and filters. Awaiting response includes new tickets and customer replies.</p><Select value={sort} onValueChange={value => { setSort(value); setPage(1) }}><SelectTrigger aria-label="Sort tickets" className="h-8 w-[160px] bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="newest">Newest first</SelectItem><SelectItem value="oldest">Oldest first</SelectItem><SelectItem value="updated">Recently updated</SelectItem></SelectContent></Select></div>
    <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><Table><TableHeader className="bg-slate-50/70"><TableRow><TableHead className="pl-5">Ticket</TableHead><TableHead>Subject</TableHead><TableHead>Customer</TableHead><TableHead>Plan</TableHead><TableHead>Status</TableHead><TableHead>Last activity (IST)</TableHead><TableHead className="pr-5 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>
      {loading ? <TableRow><TableCell colSpan={7} className="h-48 text-center"><Loader2 className="mx-auto mb-3 h-5 w-5 animate-spin text-gold-deep"/>Loading tickets...</TableCell></TableRow> : error ? <TableRow><TableCell colSpan={7} className="h-48 text-center"><AlertCircle className="mx-auto mb-3 h-6 w-6 text-rose-500"/><p className="mb-3">{error}</p><Button variant="outline" onClick={() => setRefresh(value => value + 1)}>Try again</Button></TableCell></TableRow> : !tickets.length ? <TableRow><TableCell colSpan={7} className="h-48 text-center"><MessageSquare className="mx-auto mb-3 h-7 w-7 text-gold-deep"/><p className="font-medium">No tickets found</p><p className="mt-1 text-sm text-muted-foreground">Try another status or adjust your filters.</p><Button variant="ghost" className="mt-2 text-gold-deep" onClick={reset}>Clear filters</Button></TableCell></TableRow> : tickets.map(ticket => <TableRow key={ticket._id} className="hover:bg-gold-soft/20"><TableCell className="pl-5"><button className="whitespace-nowrap font-mono text-xs text-gold-deep hover:underline" onClick={() => setSelectedId(ticket._id)}>{ticket.number}</button></TableCell><TableCell className="min-w-[230px] max-w-[320px]"><button className="block max-w-full truncate text-left font-medium hover:text-gold-deep" title={ticket.subject} onClick={() => setSelectedId(ticket._id)}>{ticket.subject}</button>{ticketNeedsReply(ticket) && <p className="mt-1 text-xs text-amber-700">{ticket.lastReplyBy === "customer" ? "Customer replied · Awaiting response" : "Awaiting first response"}</p>}</TableCell><TableCell className="min-w-[200px]"><p className="font-medium">{ticket.name || "Customer"}</p><p className="mt-1 text-xs text-muted-foreground">{ticket.email}</p>{ticket.organization && <p className="mt-1 text-xs text-muted-foreground">{ticket.organization}</p>}</TableCell><TableCell><Badge variant="outline" className={cn("capitalize font-normal", ticket.plan !== "free" && "border-gold/20 bg-gold-soft text-gold-deep")}>{ticket.plan}</Badge></TableCell><TableCell><Badge variant="outline" className={cn("gap-1.5 whitespace-nowrap rounded-full border-0 px-2.5 py-1",colors[ticket.status])}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{TICKET_LABELS[ticket.status]}</Badge></TableCell><TableCell className="whitespace-nowrap text-xs text-muted-foreground"><p>{emailLogDate(ticket.updatedAt || ticket.createdAt)}</p><p className="mt-1">{ticket.lastReplyBy === "customer" ? "Customer replied" : ticket.lastReplyBy === "admin" ? "Support replied" : "Ticket received"}</p></TableCell><TableCell className="pr-4 text-right"><Button variant="ghost" size="icon" aria-label={`View ticket ${ticket.number}`} onClick={() => setSelectedId(ticket._id)}><Eye className="h-4 w-4"/></Button></TableCell></TableRow>)}
    </TableBody></Table></div>
    <div className="flex flex-wrap items-center justify-between gap-4 text-sm"><p className="text-muted-foreground">{loading ? "Loading results…" : error ? "Results unavailable" : `Showing ${pagination.total ? (pagination.page-1)*pagination.limit+1 : 0} to ${Math.min(pagination.page*pagination.limit,pagination.total)} of ${pagination.total} tickets`}</p><div className="flex flex-wrap items-center gap-2"><Select value={limit} onValueChange={value => { setLimit(value); setPage(1) }}><SelectTrigger aria-label="Rows per page" className="h-9 w-[100px] bg-white"><SelectValue/></SelectTrigger><SelectContent>{["10","20","50"].map(value => <SelectItem key={value} value={value}>{value} rows</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" aria-label="Previous page" disabled={loading || !!error || pagination.page <= 1} onClick={() => setPage(pagination.page-1)}><ChevronLeft className="h-4 w-4"/></Button><span className="text-xs text-muted-foreground">Page {pagination.page} of {pagination.totalPages}</span><Button variant="outline" size="sm" aria-label="Next page" disabled={loading || !!error || pagination.page >= pagination.totalPages} onClick={() => setPage(pagination.page+1)}><ChevronRight className="h-4 w-4"/></Button></div></div>
  </div></main><TicketDialog id={selectedId} onClose={() => setSelectedId(null)} onUpdated={() => setRefresh(value => value+1)}/></>
}
